export const API_GET = "API_GET";
export const API_POST = "API_POST";
export const API_PUT = "API_PUT";
export const API_DELETE = "API_DELETE";
export const FETCH_FAILED = "FETCH_FAILED";

export const EXECUTE_REDIS_COMMAND_SUCCESS = "EXECUTE_REDIS_COMMAND_SUCCESS";
export const EXECUTE_REDIS_COMMAND_FAILED = "EXECUTE_REDIS_COMMAND_FAILED";
export const EXECUTE_REDIS_COMMAND_FETCH = "EXECUTE_REDIS_COMMAND_FETCH";
export const FATCH_REDIS_COMMAND_TIP_SUCCESS = "FATCH_REDIS_COMMAND_TIP_SUCCESS";
export const ADD_CONSOLE_TEXT = "ADD_CONSOLE_TEXT";
export const CHANGE_INPUT_TEXT = "CHANGE_INPUT_TEXT";

export const CREATE_REDIS_CONNECTION_SUCCESS = "CREATE_REDIS_CONNECTION_SUCCESS";
export const EDIT_REDIS_CONNECTION_SUCCESS = "EDIT_REDIS_CONNECTION_SUCCESS";
export const REMOVE_REDIS_CONNECTION_SUCCESS = "REMOVE_REDIS_CONNECTION_SUCCESS";
export const FATCH_REDIS_CONNECTION_SUCCESS = "FATCH_REDIS_CONNECTION_SUCCESS";
export const QUERY_REDIS_CONNECTION_SUCCESS = "QUERY_REDIS_CONNECTION_SUCCESS";
export const CHANGE_REDIS_CONNECTION_MODAL_VISIBLE = "CHANGE_REDIS_CONNECTION_MODAL_VISIBLE";
export const TEST_REDIS_CONNECTION_FETCH = "TEST_REDIS_CONNECTION_FETCH";
export const TEST_REDIS_CONNECTION = "TEST_REDIS_CONNECTION";
export const DISCONNECT_REDIS_CONNECTION = "DISCONNECT_REDIS_CONNECTION";

export const CREATE_REDIS_COLLECTION_SUCCESS = "CREATE_REDIS_COLLECTION_SUCCESS";
export const CREATE_REDIS_COLLECTION_FAILED = "CREATE_REDIS_COLLECTION_FAILED";
export const FATCH_REDIS_COLLECTION_SUCCESS = "FATCH_REDIS_COLLECTION_SUCCESS";
export const REMOVE_REDIS_COLLECTION_SUCCESS = "REMOVE_REDIS_COLLECTION_SUCCESS";